/**********************************************************************************************************************
 * \file GTM_TOM0_Pwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_TOM0_Pwm.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_PwmHl.h"


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PWM_FREQ_HZ               10000
#define PWM_DEAD_TIME             2e-6
#define PWM_MIN_PULSE_TIME        1.0e-6

#define PHASE_U_HS                      &IfxGtm_TOM0_1_TOUT86_P14_6_OUT
#define PHASE_U_LS                      &IfxGtm_TOM0_2_TOUT88_P14_8_OUT
#define PHASE_V_HS                      &IfxGtm_TOM0_3_TOUT89_P14_9_OUT
#define PHASE_V_LS                      &IfxGtm_TOM0_4_TOUT90_P14_10_OUT
#define PHASE_W_HS                      &IfxGtm_TOM0_5_TOUT91_P13_0_OUT
#define PHASE_W_LS                      &IfxGtm_TOM0_6_TOUT92_P13_1_OUT


#define ADC_CHANNEL_I_ALPHA       IfxVadc_ChannelId_0
#define ADC_CHANNEL_I_BETA        IfxVadc_ChannelId_1
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    IfxGtm_Tom_Timer    timer;
    IfxGtm_Tom_PwmHl    pwm;
    Ifx_TimerValue      pwmOnTimes[3];

    IfxGtm_Tom_Timer_Config timerConfig;
    IfxGtm_Tom_PwmHl_Config pwmHlConfig;
} Pwm3PhaseOutput;
Pwm3PhaseOutput g_pwm3PhaseOutput;


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
uint32 nrCntrInterrupt_u32 = 0;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(interruptGtmTom, 0, 10);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void interruptGtmTom(void)
{
    IfxGtm_Tom_Timer_acknowledgeTimerIrq(&g_pwm3PhaseOutput.timer);
    nrCntrInterrupt_u32++;
}
void initGtmTomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM);


    IfxGtm_Tom_Timer_initConfig(&g_pwm3PhaseOutput.timerConfig, &MODULE_GTM);
    g_pwm3PhaseOutput.timerConfig.base.frequency = PWM_FREQ_HZ;
    g_pwm3PhaseOutput.timerConfig.base.isrPriority = 10;
    g_pwm3PhaseOutput.timerConfig.base.isrProvider = IfxSrc_Tos_cpu0;
    g_pwm3PhaseOutput.timerConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;
    g_pwm3PhaseOutput.timerConfig.tom = IfxGtm_Tom_0;
    g_pwm3PhaseOutput.timerConfig.timerChannel = IfxGtm_Tom_Ch_0;
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);
    IfxGtm_Tom_Timer_init(&g_pwm3PhaseOutput.timer, &g_pwm3PhaseOutput.timerConfig);

    IfxGtm_Tom_ToutMapP ccx[] = {PHASE_U_HS, PHASE_V_HS, PHASE_W_HS};
    IfxGtm_Tom_ToutMapP coutx[] = {PHASE_U_LS, PHASE_V_LS, PHASE_W_LS};

    IfxGtm_Tom_PwmHl_initConfig(&g_pwm3PhaseOutput.pwmHlConfig);
    g_pwm3PhaseOutput.pwmHlConfig.base.channelCount = sizeof(ccx) / sizeof(IfxGtm_Tom_ToutMapP);
    g_pwm3PhaseOutput.pwmHlConfig.base.deadtime = PWM_DEAD_TIME;
    g_pwm3PhaseOutput.pwmHlConfig.base.minPulse = PWM_MIN_PULSE_TIME;
    g_pwm3PhaseOutput.pwmHlConfig.base.outputMode = IfxPort_OutputMode_pushPull;
    g_pwm3PhaseOutput.pwmHlConfig.base.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;
    g_pwm3PhaseOutput.pwmHlConfig.base.ccxActiveState = Ifx_ActiveState_high;
    g_pwm3PhaseOutput.pwmHlConfig.base.coutxActiveState = Ifx_ActiveState_high;
    g_pwm3PhaseOutput.pwmHlConfig.ccx = ccx;
    g_pwm3PhaseOutput.pwmHlConfig.coutx = coutx;
    g_pwm3PhaseOutput.pwmHlConfig.timer = &g_pwm3PhaseOutput.timer;
    g_pwm3PhaseOutput.pwmHlConfig.tom   = g_pwm3PhaseOutput.timerConfig.tom;

    IfxGtm_Tom_PwmHl_init(&g_pwm3PhaseOutput.pwm, &g_pwm3PhaseOutput.pwmHlConfig);
    IfxGtm_Tom_PwmHl_setMode(&g_pwm3PhaseOutput.pwm, Ifx_Pwm_Mode_centerAligned);
    IfxGtm_Tom_Timer_run(&g_pwm3PhaseOutput.timer);
}


