/**********************************************************************************************************************
 * \file ThreePhase_Pwm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CommonDefinitions.h"
#include "ThreePhase_Pwm.h"
#include "transform_Park.h"
#include "transform_Clarke.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PHASE_U_HS                      &IfxGtm_TOM0_1_TOUT86_P14_6_OUT
#define PHASE_U_LS                      &IfxGtm_TOM0_2_TOUT88_P14_8_OUT
#define PHASE_V_HS                      &IfxGtm_TOM0_3_TOUT89_P14_9_OUT
#define PHASE_V_LS                      &IfxGtm_TOM0_4_TOUT90_P14_10_OUT
#define PHASE_W_HS                      &IfxGtm_TOM0_5_TOUT91_P13_0_OUT
#define PHASE_W_LS                      &IfxGtm_TOM0_6_TOUT92_P13_1_OUT

#define PWM_FREQ_HZ                     10000                            /* Define the PWM Switching Frequency value in Hz */
#define GTM_TOM_MASTER                  IfxGtm_Tom_0
#define GTM_TOM_MASTER_TIMER_CH         IfxGtm_Tom_Ch_0
#define PWM_DEAD_TIME                   2e-6                           /* Define the dead time in s.                     */
#define PWM_MIN_PULSE_TIME              1e-6                           /* Define the minimum pulse allowed in s.         */

#define MOTOR_POLES                     3
#define VOLTAGE_POWER_SUPPLY            12.0f
#define VOLTAGE_AMPLITUDE               10.0f  // 电压幅值

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
Pwm3PhaseOutput g_pwm3PhaseOutput;

IfxGtm_Tom_Timer_Config timerConfig; /* Timer configuration              */
IfxGtm_Tom_PwmHl_Config pwmHlConfig;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
float32 zero_electric_angle = 0;
float32 shaft_angle = 0;
float32 Ualpha_r32 = 0;
float32 Ubeta_r32 = 0;
float32 Ua = 0;
float32 Ub = 0;
float32 Uc = 0;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static float32 electricalAngle (float32 shaft_angle, int pole_pairs);
static float32 normalizeAngle (float32 angle);
static void setPwm (float32 Ua, float32 Ub, float32 Uc);
static void setPhaseVoltage (float32 Uq, float32 Ud, float32 angle_el);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
float32 electricalAngle (float32 shaft_angle, int pole_pairs)
{
    return (shaft_angle * pole_pairs);
}
float32 normalizeAngle (float32 angle)
{
    float32 ag = (float32)fmod(angle, 2 * PI);
    return ag >= 0 ? ag : (ag + 2 * PI);
}
void setPwm (float32 Ua, float32 Ub, float32 Uc)
{
    Ua = LIMIT(0.0f, Ua, VOLTAGE_AMPLITUDE);
    Ub = LIMIT(0.0f, Ub, VOLTAGE_AMPLITUDE);
    Uc = LIMIT(0.0f, Uc, VOLTAGE_AMPLITUDE);
    Ifx_TimerValue period;
    period = g_pwm3PhaseOutput.pwm.timer->base.period;
    float32 dc_a = LIMIT(0.0f, Ua/VOLTAGE_POWER_SUPPLY, VOLTAGE_AMPLITUDE);
    float32 dc_b = LIMIT(0.0f, Ub/VOLTAGE_POWER_SUPPLY, VOLTAGE_AMPLITUDE);
    float32 dc_c = LIMIT(0.0f, Uc/VOLTAGE_POWER_SUPPLY, VOLTAGE_AMPLITUDE);
    g_pwm3PhaseOutput.pwmOnTimes[0] = dc_a * period;
    g_pwm3PhaseOutput.pwmOnTimes[1] = dc_b * period;
    g_pwm3PhaseOutput.pwmOnTimes[2] = dc_c * period;
    /* Update new PWM duty cycles */
    IfxGtm_Tom_Timer_disableUpdate(&g_pwm3PhaseOutput.timer);
    IfxGtm_Tom_PwmHl_setOnTime(&g_pwm3PhaseOutput.pwm, g_pwm3PhaseOutput.pwmOnTimes);
    IfxGtm_Tom_Timer_applyUpdate(&g_pwm3PhaseOutput.timer);
}
void setPhaseVoltage (float32 Uq, float32 Ud, float32 angle_el)
{
    angle_el = normalizeAngle(angle_el + zero_electric_angle);
    transform_iPark(Uq, Ud, angle_el, &Ualpha_r32, &Ubeta_r32);
    transform_iClarke(Ualpha_r32, Ubeta_r32, &Ua, &Ub, &Uc);
    setPwm(Ua, Ub, Uc);
}

float32 velocityOpenLoop (float32 target_velocity)
{
    shaft_angle = normalizeAngle(shaft_angle + target_velocity * (10.0 * 1e-3f));
    float32 Uq = VOLTAGE_AMPLITUDE;
    setPhaseVoltage(Uq, 0, electricalAngle(shaft_angle, MOTOR_POLES));
    return Uq;
}

extern void ThreePhase_Pwm_initGtmTom (void)
{
    IfxGtm_enable(&MODULE_GTM);

    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);
    /* Enable the FXU clock                         */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    IfxGtm_Tom_Timer_initConfig(&timerConfig, &MODULE_GTM); /* Initialize default parameters    */
    timerConfig.base.frequency = PWM_FREQ_HZ; /* Set timer frequency              */
    timerConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0; /* Define the CMU clock used        */
    timerConfig.tom = GTM_TOM_MASTER; /* Define the timer used            */
    timerConfig.timerChannel = GTM_TOM_MASTER_TIMER_CH; /* Define the channel used          */
    IfxGtm_Tom_Timer_init(&g_pwm3PhaseOutput.timer, &timerConfig); /* Initialize the TOM               */

    IfxGtm_Tom_ToutMapP ccx[] = {
    PHASE_U_HS, /* PWM High-side 1 */
    PHASE_V_HS, /* PWM High-side 2 */
    PHASE_W_HS /* PWM High-side 3 */
    };
    IfxGtm_Tom_ToutMapP coutx[] = {
    PHASE_U_LS, /* PWM Low-side 1 */
    PHASE_V_LS, /* PWM Low-side 2 */
    PHASE_W_LS /* PWM Low-side 3 */
    };

    /* Initialize the configuration structure to default */
    IfxGtm_Tom_PwmHl_initConfig(&pwmHlConfig);
    pwmHlConfig.base.channelCount = 3;
    pwmHlConfig.base.deadtime = PWM_DEAD_TIME;
    pwmHlConfig.base.minPulse = PWM_MIN_PULSE_TIME;
    pwmHlConfig.base.outputMode = IfxPort_OutputMode_pushPull;
    pwmHlConfig.base.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;
    pwmHlConfig.base.ccxActiveState = Ifx_ActiveState_high;
    pwmHlConfig.base.coutxActiveState = Ifx_ActiveState_high;

    pwmHlConfig.ccx = ccx; /* Assign the channels for High-side switches   */
    pwmHlConfig.coutx = coutx; /* Assign the channels for Low-side switches    */
    pwmHlConfig.timer = &g_pwm3PhaseOutput.timer;
    pwmHlConfig.tom = timerConfig.tom;

    IfxGtm_Tom_PwmHl_init(&g_pwm3PhaseOutput.pwm, &pwmHlConfig);
    IfxGtm_Tom_PwmHl_setMode(&g_pwm3PhaseOutput.pwm, Ifx_Pwm_Mode_centerAligned);
    IfxGtm_Tom_Timer_updateInputFrequency(&g_pwm3PhaseOutput.timer);

    IfxGtm_Tom_Timer_run(&g_pwm3PhaseOutput.timer);

    IfxGtm_Tom_Timer_disableUpdate(&g_pwm3PhaseOutput.timer);
    IfxGtm_Tom_PwmHl_setOnTime(&g_pwm3PhaseOutput.pwm, g_pwm3PhaseOutput.pwmOnTimes);
    IfxGtm_Tom_Timer_applyUpdate(&g_pwm3PhaseOutput.timer);

    //TODO 添加下降沿中断
}



